#===============================================================================
version: '3'

#===============================================================================
services:
  drupal:
    image: iyuuya/drupal:latest
    ports:
      - 8080:80
    volumes:
      - ./:/data/drupal
    links:
      - db
    networks:
      - d8esnet

  db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - d8esnet

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
    container_name: elasticsearch
    environment:
      - cluster.name=d8es-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - d8esnet
  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
    container_name: elasticsearch2
    environment:
      - cluster.name=d8es-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    networks:
      - d8esnet

#===============================================================================
volumes:
  mysqldata:
    driver: local
  esdata1:
    driver: local
  esdata2:
    driver: local

#===============================================================================
networks:
  d8esnet:
